export default Strings = {
  phoneNumber: 'Phone Number',
  Otp: 'OTP',
  placeHolderOtp: 'Please enter OTP here',
  placeHolderPhoneNumber: 'Please enter phone-number here',
  errorPhoneNumber: 'Please enter valid phone-number',
  Login: 'Login',
  SignUp: 'Sign Up',
  GetOTP: 'Get OTP',
  tryAgain: 'Try Again',
  ResendOTP: 'Resend OTP',
  VerifyOTP: 'Verify OTP',
  Next: 'Next',
  Confirm: 'Confirm',
  Logout: 'Logout',
  Setting: 'More Setting',
  BirthDate: 'Date of Birth',
  placeHolderBirthDate: 'Please enter birthdate here',
  errorBirthDate: 'Please enter valid birthdate',
  FirstName: 'First Name',
  Name: 'Name',
  placeHolderFirstName: 'Please enter first name here',
  errorFirstName: 'Please enter valid first name',
  LastName: 'Last Name',
  placeHolderLastName: 'Please enter last name here',
  placeHolderOther: 'Other',
  errorLastName: 'Please enter valid last name',
  Class: 'Class',
  placeHolderClass: 'Please enter class here',
  errorClass: 'Please enter valid class',
  Age: 'Age',
  placeHolderAge: 'Please enter age here',
  errorAge: 'Please enter valid age',
  Address: 'Address',
  placeHolderAddress: 'Please enter address here',
  errorAddress: 'Please enter valid address',
  Other: 'Other',
  errorOther: 'Please enter valid other option',
  Address1: 'Address Line1',
  Address2: 'Address Line2',
  Pin: 'Pin-Code',
  City: 'City',
  State: 'State',

  placeHolderAddress1: 'Please enter address line1 here',
  placeHolderAddress2: 'Please enter address line2 here',
  placeHolderCity: 'Please enter city here',
  placeHolderPin: 'Please enter pin code here',
  placeHolderState: 'Please enter state here',

  errorAddress1: 'Please enter valid address line1',
  errorAddress2: 'Please enter valid address line2',
  errorPin: 'Please enter valid pin code',
  errorCity: 'Please enter valid city',
  errorState: 'Please enter valid state',

  Profile: 'Profile',
  Crates: 'Crates',
  Detail: 'Detail',
  Buy: 'Buy',
  MyList: 'My List',
  GETATLASCRATE: 'GET ATLAS CRATE',
  AddAddress: 'Add Address',

  GetStarted: 'Get Started',
  YouSubscription: 'Your Subscription',
  YourCrate: 'Select your crates',
  YourMultipleCrate: 'Select your multiple crates',
};
